version: '3'

services:
  db:
    image: postgres
    container_name: bookshop-db
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - local_db_data:/var/lib/postgres/
    networks:
      - bookshop-network

volumes:
  local_db_data: {}

networks:
  bookshop-network: