version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file: ./server/.env
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
      # - ${DB_PORT}:5432
    volumes:
      - local_db_data:/var/lib/postgres/
  # api:
  #   depends_on:
  #     - db
  #   restart: unless-stopped
  #   ports:
  #     - ${API_PORT}:3000
  #   env_file: ./server/.env

volumes:
  local_db_data: {}