import type { Metadata } from "next";
import RtkProvider from "@/providers/rtk";
import QueryProvider from "@/providers/query";
import { Inter, Poppins } from "next/font/google";
import store from "@/store";
import Navbar from "@/components/navbar";
import SiteTitle from "@/components/site-title";
import Notification from "@/components/notification";
import { Toaster } from "@/components/toaster";

import "./globals.css";

import "@smastrom/react-rating/style.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({
  display: "swap",
  subsets: ["latin"],
  weight: "500",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Welcome to Bookshop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body suppressHydrationWarning={true}>
        <main className="flex min-h-screen flex-col items-center justify-start p-8 mx-2 md:mx-10 mb-16 gap-16">
          <RtkProvider store={store}>
            <Toaster
              toastOptions={{
                unstyled: false,
                classNames: {
                  description: "inline-block text-red-400",
                  actionButton: "bg-zinc-400",
                  cancelButton: "bg-orange-400",
                  closeButton: "bg-lime-400",
                },
              }}
            />
            <QueryProvider>
              <Navbar />
              <SiteTitle
                title="bookshop"
                slogan="Your Online Destination for Literary Exploration and Inspiration"
              />
              <Notification />
              {children}
            </QueryProvider>
          </RtkProvider>
        </main>
      </body>
    </html>
  );
}
